[project]
name = "linguistic-engineering-pjatk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.4",
    "networkx>=3.2.1",
    "nltk>=3.9.1",
    "scikit-learn>=1.6.1",
]
